
apiVersion: v1
kind: Secret
metadata:
  name: workflow-backend-secrets
type: Opaque
stringData:
  datasource-url: jdbc:postgresql://postgres:5432/promo-db
  datasource-username: promo
  datasource-password: promo
